### ISSUE TITLE
Python Libraries supported?

### ISSUE THREAD

**Issue by cyberboysumanjay** [cloudflare/python-worker-hello-world#3]
Hey, I just explored this and the first impressions reflect that this thing uses Transcrypt to change python code to JavaScript and run it's equivalent code on workers.
If I'm not wrong, In this way adding support of all python libraries is somewhat impossible.

Is there any way to support them as of now?

**Comment by koeninger** [comment]
The readme for the this project, our blog post describing support for compile to JS languages at https://blog.cloudflare.com/cloudflare-workers-announces-broad-language-support/ and the transcrypt docs at http://transcrypt.org/documentation#faq are pretty up front about what this and what the benefits and limitations are.

Python libraries that are purely python are likely to work, as long as you stay under the 1mb workers limit. Python libraries that depend on native code (eg. C or Fortran wrappers) won't work.  Transcrypt does have an implementation of significant portions of the Numpy interface.

**Comment by kichappa** [comment]
I understand that purely python can be used. But, I keep getting an error that the libraries are missing. 

```
Error while compiling (offending file last):
        File '...location/app-workers/index.py', line 13, at import of:
        File 'separate_pythonfile.py', line 13, namely:

        Import error, can't find any of:
                Drive:/...location/app-workers/scipy/interpolate/interp2d.py
                Drive:/...location/app-workers/scipy/interpolate/interp2d.js
```

Any pointers on how I can use libraries on the worker will be appreciated.
