### ISSUE TITLE
Python Libraries on Worker

### ISSUE THREAD

**Issue by kichappa** [cloudflare/python-worker-hello-world#5]
I see in #3 that purely python can be used. But, I keep getting an error that the libraries are missing. 

```
Error while compiling (offending file last):
        File '...location/app-workers/index.py', line 13, at import of:
        File 'separate_pythonfile.py', line 13, namely:

        Import error, can't find any of:
                Drive:/...location/app-workers/scipy/interpolate/interp2d.py
                Drive:/...location/app-workers/scipy/interpolate/interp2d.js
```

Any pointers on how I can use libraries on the worker will be appreciated.

**Comment by jclee** [comment]
Per #3: "Python libraries that depend on native code (eg. C or Fortran
wrappers) won't work."

Scipy -- and numpy, which it relies on -- are not pure Python; they depend
heavily on native C and Fortran code modules.

**Comment by kichappa** [comment]
Okay.

What about `urllib`? It's showing the same error.

**Comment by jclee** [comment]
According to an answer on this StackOverflow page, it looks like transcrypt's standard library replacement doesn't provide an implementation for urllib yet: https://stackoverflow.com/questions/62929787/how-can-i-read-the-contents-of-an-url-with-transcrypt-where-is-urlopen-locate

However, the answer does give a workaround for `urlopen()` that maps to JS's `fetch()` API.

**Comment by kichappa** [comment]
Thanks for the information. I appreciate it!
